import React from 'react';
import { AlertTriangle, ShieldAlert } from 'lucide-react';

export const DisclaimerBanner: React.FC<{ compact?: boolean }> = ({ compact = false }) => {
  if (compact) {
    return (
      <div className="bg-amber-950/40 border border-amber-500/30 px-3 py-1 rounded text-xs text-amber-300 flex items-center gap-1.5">
        <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0 text-amber-400" />
        <span><strong>Research estimate only.</strong> ORVEXA is not an operational collision-avoidance authority.</span>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-r from-amber-950/60 via-amber-900/30 to-amber-950/60 border-y border-amber-500/30 px-4 py-2 text-xs text-amber-200 flex items-center justify-between shadow-inner">
      <div className="flex items-center gap-2 max-w-5xl mx-auto">
        <ShieldAlert className="w-4 h-4 text-amber-400 flex-shrink-0" />
        <div>
          <span className="font-semibold text-amber-300">SCIENTIFIC RESEARCH DEMONSTRATOR: </span>
          <span>
            Predictions and conformal intervals generated by ORVEXA are academic research estimates based on ESA Conjunction Data Messages (CDMs).
            This tool does not constitute operational flight safety advice or space-traffic management decisions.
          </span>
        </div>
      </div>
    </div>
  );
};
